[book]
authors = ["Ron Eggler", "Matin Lotfaliei"]
language = "en"
multilingual = false
src = ""
title = "MistySOM Wiki"
description = "You are at the right place to access documentation, information or support for MistySOM."
logo = "files/img/logo.png"

[output.html]
git-repository-url = "https://github.com/MistySOM"
git-repository-icon = "fa-github"
cname = "https://wiki.mistysom.com"
no-section-label = true
additional-css = ["files/custom.css"]
