name: Deploy mdbook

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    deploy:
        runs-on: DC01
        steps:
            - uses: actions/checkout@v3

            - name: Build mdbook
              run: C:\actions-runner\mdbook.exe build -d "C:\actions-runner\wiki.mistysom.com"

