name: Fast forward master if develop is approved

on:
  pull_request_review:
    types: [submitted]

jobs:
  fast_forward_job:
    name: Fast Forward
    if: github.event.pull_request.base.ref == 'master' && github.event.review.state == 'approved'  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
        
      - name: Fast Forward PR
        run: |
          git merge origin/develop --ff-only
          git push
